name: precommit

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Pre-commit Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: pip install uv

      - name: Type checking with ty
        run: uvx ty check .

      - name: Ruff lint
        run: uvx ruff check .
