name: cron_update_schedules_spring

on:
  schedule: # every day at 21:00 from 1 Feb to 31 Mar and from 1 Aug to 31 Oct
    - cron: '0 21 * 2-3,8-10 *'
  workflow_dispatch: # manually trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner.
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: pip install uv
      
      - name: uv sync
        run: uv sync
          
      - name: execute py script # run update_schedules.py
        run: uv run update_schedules.py
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_URL: ${{ secrets.DB_URL }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        
      